const BOOKING_TYPE_LAB = 'lab';
const BOOKING_TYPE_DOCTOR = 'doctor';


const ROLE_PATIENT = 'ROLE_PATIENT';
const ROLE_STAFF = 'ROLE_STAFF';
const ROLE_DOCTOR = 'ROLE_DOCTOR';
const ROLE_ADMIN = 'ROLE_ADMIN';


export {
  BOOKING_TYPE_DOCTOR, BOOKING_TYPE_LAB,

  ROLE_PATIENT, ROLE_STAFF, ROLE_DOCTOR, ROLE_ADMIN,
};

