const specialities = [
  'Anaesthesiology',
  'Cardiology',
  'Cardiothoracic Surgery',
  'Dermatology',
  'Diagnostic Radiology',
  'Emergency Medicine',
  'Endocrinology',
  'Gastroenterology',
  'General Surgery',
  'Geriatric Medicine',
  'Haematology',
  'Hand Surgery',
  'Infectious Diseases',
  'Internal Medicine',
  'Medical Oncology',
  'Neurology',
  'Neurosurgery',
  'Nuclear Medicine',
  'Obstetrics & Gynaecology',
  'Occupational Medicine',
  'Ophthalmology',
  'Orthopaedic Surgery',
  'Otorhinolaryngology/ENT',
  'Paediatric Medicine',
  'Paediatric Surgery',
  'Pathology',
  'Plastic Surgery',
  'Psychiatry',
  'Public Health',
  'Radiation Oncology',
  'Rehabilitation Medicine',
  'Renal Medicine',
  'Respiratory Medicine',
  'Rheumatology',
  'Urology',
  'Aviation Medicine',
  'Intensive Care Medicine',
  'Neonatology',
  'Palliative Medicine',
  'Sports Medicine',
  'Paediatric Nephrology',
  'Paediatric Cardiology',
  'Paediatric Intensive Care',
  'Paediatric Gastroenterology',
  'Paediatric Haematology & Oncology',
].sort();

export { specialities };
