name: Build and deploy to staging

on:
  push:
    branches: ["track/staging"]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ "track/staging" ]
  workflow_dispatch:
    inputs:
      build_id:
        description: 'unique build id'
        required: true
        type: string    

env:
  A: ''

permissions:
  contents: read

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
  
