#new s3 configured
name: Build and deploy to S3

on:
  push:
    branches: ["main", "track/*"]
  workflow_dispatch:
    inputs:
      BUILD_ID:
        description: 'Unique Build Id'
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install packages
        run: npm ci --no-fund --no-update-notifier
      - name: Run unit tests
        run: npm run test:unit
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
      - name: Set build info
        run: |
          if [[ ${{ github.event_name == 'push' }} ]]; then
            echo "VITE_BUILD_INFO=${{ github.SHA }}__${{ github.WORKFLOW_SHA }}" >> $GITHUB_ENV
          else
            echo "VITE_BUILD_INFO=MANUAL__${{ inputs.BUILD_ID }}__${{ github.WORKFLOW_SHA }}" >> $GITHUB_ENV
          fi
      - name: Build for staging
        run: npm run build -- --mode staging
      - name: '[DEBUG] List built files'
        run: ls dist/*
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Copy files to S3
        run: |
          aws s3 cp dist s3://${{ secrets.AWS_S3_BUCKET }} --recursive

