name: Build and deploy to staging

on:
  push:
    branches: ["track/staging"]
  workflow_dispatch:
    inputs:
      BUILD_ID:
        description: 'unique build id'
        required: true
        type: string

permissions:
  contents: read

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - run: npm ci --no-fund --no-update-notifier
      - run: npm run build -- --mode staging
      - if: ${{ github.event_name == 'push' }}
        run : echo "VITE_BUILD_INFO=\"${{github.SHA}}__${{github.WORKFLOW_SHA}}\"" >> "$GITHUB_ENV"
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run : echo "VITE_BUILD_INFO=\"${{github.EVENT_NAME}}__${{inputs.BUILD_ID}}\"" >> "$GITHUB_ENV"
      - run: ls
      - run: ls dist/*

