name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '**.js'
      - '**.vue'
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Calculate coverage
    permissions:
      pull-requests: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'npm'
      - name: Install packages
        run: npm ci --no-fund --no-update-notifier
      - name: Run unit tests
        run: npm run test:unit
        id: unit_test
      - name: Modify test coverage
        run: |
          echo '```' >> coverage/coverage.txt
          tac coverage/coverage.txt >> coverage/coverage.txt.reversed
          echo -n '```'  >> coverage/coverage.txt.reversed
          tac coverage/coverage.txt.reversed >> coverage/coverage.txt.final
      - name: Add coverage
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body-path: 'coverage/coverage.txt.final'
      - name: Mark unit test fail
        if: ${{ failure() && steps.unit_test.conclusion == 'failure'}}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: 'Unit test failed'
      - name: Install OWASP Dependency Check
        run: |
          VERSION=$(curl -s https://jeremylong.github.io/DependencyCheck/current.txt)
          curl -Ls "https://github.com/jeremylong/DependencyCheck/releases/download/v$VERSION/dependency-check-$VERSION-release.zip" --output dependency-check.zip
          unzip dependency-check.zip
      - name: Run scan with ODC
        run: |
          dependency-check/bin/dependency-check.sh --project "bitcoin" --scan . -f HTML -o ODC-report.html
          zip odc.zip ODC-report.html debug.log
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sast report
          path: odc.zip

